name: Run a testing workflow

on:
  - pull_request:
      types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: sleep
        run: |
          sleep 120
